# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Faino < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lex-unix/faino/releases/download/v0.0.1/faino-mac-x86_64.tar.gz"
      sha256 "47a548794e12637ab85d12da0feee81641dc54aae7d5554db352aa7791c91732"

      def install
        bin.install "faino"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lex-unix/faino/releases/download/v0.0.1/faino-mac-arm64.tar.gz"
      sha256 "9337ac48487198e8a7f253b3335c2a966a8645006ac06ed1498f714804b0fdda"

      def install
        bin.install "faino"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/lex-unix/faino/releases/download/v0.0.1/faino-linux-x86_64.tar.gz"
      sha256 "25c8e0c1361f12525a9442084c788de77b6a3d7b1af0a6881bd7170e569be62b"
      def install
        bin.install "faino"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/lex-unix/faino/releases/download/v0.0.1/faino-linux-arm64.tar.gz"
      sha256 "e51805ed5cc667c236b21d708a56dabbe410bd75eb0b0f66099fd198ade06c90"
      def install
        bin.install "faino"
      end
    end
  end
end
